### PR TITLE
added vim keybindings

### PR DESCRIPTION
**Pull request by aarya-bhatia**
- Add key bindings for h/j/k/l events to keys.go

### CODE REVIEW

**Comment by codesoap** [comment]
Hi Aarya,
I'm not opposed to this change, but would request some changes, if you want to go through with it. Are you still interested?

**Comment by aarya-bhatia** [comment]
> Hi Aarya, I'm not opposed to this change, but would request some changes, if you want to go through with it. Are you still interested?

Hello, I'm down to work on some changes. Please let me know what you have in mind.

**Comment by codesoap** [comment]
Alright cool :-) Here's what I'd like to see changed:
- You have committed the `tags` file. Please exclude it.
- Since `handleRightKey` and `handleLeftKey` only contain one line of code, I don't see the need for functions here. Just keep the original code.
- I feel like `handleUpKey` and `handleDownKey` are not ideal function names, since the functions are not only used for the "up" and "down" keys. What do you think about `handlePrevKey` and `handleNextKey`?
- It's just personal preference, but could you place the new functions below the `handleKeyEvents` function? I prefer my code files to be readable from top to bottom, whenever possible.
- Please mention the newly added key bindings in `keyBindingInfo` and in `README.md`. Maybe just separate the new keys with a comma, like `up, k: highlight previous song`.

Feel free to just ammend the existing commit and force push the changes.

**Comment by aarya-bhatia** [comment]
Hey, thank you for your response! I made the changes you requested. The new keybindings include h,j,k,l (same as arrow keys), and J, K (same as ALT+down/up) because usually ALT+j/k is already used by my window manager. Also, for convenience, I included a small git ignore file and Makefile. Please let me know if it looks okay to you.

**Comment by codesoap** [comment]
Thanks for implementing my requests. Most looks good now, but I have a few new remarks:
- The `.gitignore` and `Makefile` files have nothing to do with keybindings, so they should not be part of this pull request. However, I can already say that I wouldn't accept pull requests for those, since the README file already describes the installation without a Makefile and I'm not a fan of `.gitignore` files that contain files from individual tools (e.g. the tags file).
- `keyBindingInfo` now contains more spaces than necessary. The "`:` column" should not be further to the right than necessary.
- The `alt+j` and `alt+k` key bindings exist but were not documented.
- I'm hesitant to include the `J` and `K` keybindings. I feel like not many users are using the `alt` key for global keybindings, so I would leave this edge case to individual configuration. Please exclude these two keybindings from this pull request.

**Comment by aarya-bhatia** [comment]
Thank you for your feedback! I have now made the fixes you requested and only committed the keys.go and README file. Please let me know if this is better.

**Comment by codesoap** [comment]
Looking good. Thanks for your contribution and patience!

**Pull request merged**
